### ISSUE TITLE
Adding a word to a factoid that's an alias breaks said alias

### ISSUE THREAD

**Issue by Eijebong** [ZoeyR/nestor#18]
```
eijebong> ~learn mew @= cats
rustybot> [notice] learned factoid: 'mew'.
sebk> ~learn mew += sebk
rustybot> [notice] edited factoid: 'mew'.
```

`~mew` is now broken :/

**Comment by ZoeyR** [comment]
This is not a bug, when you edit an alias you edit the text of the alias, which was in this case "cats" and after the edit became "cats sebk". This is intentional in case you typo the alias.
